export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_TODO_LIST = "SET_TODO_LIST";
export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const COMPLETE_TODO_ITEM = "COMPLETE_TODO_ITEM"
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM"
